project:
  type: website

website:
  title: "Holly Lopez"
  site-url: https://hollydlopez.github.io/
  description: "Information scientist investigating AI safety, abusive language detection, and content moderation systems"
  favicon: files/favicon.ico
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: false

  navbar:
    right:
      - text: About
        aria-label: "About"
        href: about/index.qmd
      - text: Projects
        aria-label: "Projects"
        href: project/index.qmd
      - text: Publications
        aria-label: "Publications"
        href: publications.html
      - icon: github
        href: https://www.github.com/hollydlopez
        aria-label: "GitHub"

  page-footer:
    left: >-
     &#169; 2025 Holly Lopez &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://linkedin.com/in/hollydlopez" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/hollydlopez" title="GitHub" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=wHSlHaAAAAAJ&hl=en" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="mailto:hdlopezl@iu.edu" title="Email" target="_blank" rel="noopener">{{< fa envelope >}}</a>
    right: []

format:
  html:
    theme:
      light: cosmo
      dark: cosmo
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute:
  freeze: auto
